import type { Metadata } from "next";
import { setRequestLocale, getTranslations } from "next-intl/server";
import { pageMetadata } from "@/lib/seo/metadata";
import { getProfile } from "@/lib/content";
import type { Locale } from "@/i18n/routing";
import { Hero } from "@/components/home/Hero";
import { SelectedWork } from "@/components/home/SelectedWork";
import { Services } from "@/components/home/Services";
import { TechStack } from "@/components/home/TechStack";
import { ExperiencePreview } from "@/components/home/ExperiencePreview";
import { CtaBand } from "@/components/home/CtaBand";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const key = locale as Locale;
  const t = await getTranslations({ locale, namespace: "home" });
  const profile = getProfile();

  return pageMetadata({
    locale: key,
    path: "/",
    title: `${profile.name[key]} — ${profile.headline[key]}`,
    description: t("intro"),
    // Generated by scripts/make-page-cards.mts.
    image: {
      url: `/og/home-${key}.jpg`,
      alt: `${profile.name[key]} — ${profile.headline[key]}`,
    },
  });
}

export default async function HomePage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <>
      <Hero />
      <SelectedWork />
      <Services />
      <TechStack />
      <ExperiencePreview />
      <CtaBand />
    </>
  );
}
