import { notFound } from "next/navigation";
import Image from "next/image";
import type { Metadata } from "next";
import { setRequestLocale, getTranslations } from "next-intl/server";
import { Link } from "@/i18n/navigation";
import { StackList } from "@/components/projects/StackList";
import { StatusLabel } from "@/components/projects/StatusLabel";
import { VideoPlayer } from "@/components/projects/VideoPlayer";
import { Gallery } from "@/components/projects/Gallery";
import { CaseStudy } from "@/components/projects/CaseStudy";
import {
  getProject,
  getProjects,
  getProjectNeighbours,
  resolveTech,
} from "@/lib/content";
import { pageMetadata } from "@/lib/seo/metadata";
import { JsonLd } from "@/components/seo/JsonLd";
import { projectSchema, breadcrumbSchema } from "@/lib/seo/jsonLd";
import { formatRange } from "@/lib/format";
import { routing, type Locale } from "@/i18n/routing";

export function generateStaticParams() {
  return routing.locales.flatMap((locale) =>
    getProjects().map((project) => ({ locale, slug: project.slug })),
  );
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string; slug: string }>;
}): Promise<Metadata> {
  const { locale, slug } = await params;
  const project = getProject(slug);
  if (!project) return {};
  const key = locale as Locale;

  return pageMetadata({
    locale: key,
    path: `/projects/${project.slug}`,
    title: project.seo?.title?.[key] ?? project.title[key],
    description: project.seo?.description?.[key] ?? project.summary[key],
    // Generated by scripts/make-og-images.mts from the project's own cover.
    image: {
      url: `/projects/${project.slug}/og.jpg`,
      alt: project.coverAlt[key],
    },
  });
}

/**
 * One column, top to bottom, at every width. The facts (status, role, client,
 * dates, stack) come right after the cover, before the long body, so the
 * reading order on a phone is the same as on a desktop. The previous sidebar
 * put them after the entire case study on small screens.
 */
export default async function ProjectPage({
  params,
}: {
  params: Promise<{ locale: string; slug: string }>;
}) {
  const { locale, slug } = await params;
  setRequestLocale(locale);

  const project = getProject(slug);
  if (!project) notFound();

  const key = locale as Locale;
  const t = await getTranslations("project");
  const common = await getTranslations("common");
  const { previous, next } = getProjectNeighbours(slug);
  const techNames = resolveTech(project.stack).map((item) => item.name);

  const facts = [
    { label: t("status"), value: <StatusLabel status={project.status} /> },
    { label: t("role"), value: project.role[key] },
    project.client ? { label: t("client"), value: project.client[key] } : null,
    {
      label: t("timeline"),
      value: (
        <span className="numeric">
          {formatRange(
            project.timeline.start,
            project.timeline.end,
            key,
            t("present"),
          )}
        </span>
      ),
    },
    { label: t("stack"), value: <StackList ids={project.stack} /> },
  ].filter((row) => row !== null);

  return (
    <article className="wrap py-8 sm:py-12">
      <JsonLd data={projectSchema({ project, locale: key, techNames })} />
      <JsonLd
        data={breadcrumbSchema({
          locale: key,
          trail: [
            { name: t("backToWork"), path: "/projects" },
            { name: project.title[key], path: `/projects/${project.slug}` },
          ],
        })}
      />

      <Link
        href="/projects"
        className="inline-flex min-h-11 items-center text-sm text-muted-foreground transition-colors hover:text-foreground"
      >
        ← {t("backToWork")}
      </Link>

      <header className="mt-4">
        <h1 className="text-2xl font-bold text-balance">
          {project.title[key]}
        </h1>
        <p className="mt-2 max-w-[60ch] text-base text-muted-foreground">
          {project.tagline[key]}
        </p>
        {project.links.live || project.links.source ? (
          <div className="mt-4 flex flex-wrap items-center gap-4">
            {project.links.live ? (
              <a
                className="btn btn-primary"
                href={project.links.live}
                target="_blank"
                rel="noopener noreferrer"
              >
                {common("visitSite")}
              </a>
            ) : null}
            {project.links.source ? (
              <a
                href={project.links.source}
                target="_blank"
                rel="noopener noreferrer"
                className="btn btn-ghost"
              >
                {common("viewSource")}
              </a>
            ) : null}
          </div>
        ) : null}
      </header>

      <Image
        src={project.cover}
        alt={project.coverAlt[key]}
        width={1600}
        height={1000}
        priority
        sizes="(min-width: 768px) 720px, 100vw"
        className="mt-8 w-full rounded-[var(--radius-lg)] border object-cover object-top shadow-[var(--shadow-hover)]"
      />

      <dl className="mt-8 grid grid-cols-[max-content_1fr] gap-x-6 gap-y-2 rounded-[var(--radius-lg)] border bg-card p-5 text-sm">
        {facts.map((row) => (
          <div key={row.label} className="contents">
            <dt className="text-muted-foreground">{row.label}</dt>
            <dd className="min-w-0">{row.value}</dd>
          </div>
        ))}
      </dl>

      <p className="mt-8 max-w-[66ch] text-base">{project.summary[key]}</p>

      <section className="mt-8">
        <h2 className="text-xl font-semibold">{t("highlights")}</h2>
        <ul className="mt-3 list-disc space-y-1.5 ps-5 text-base">
          {project.highlights.map((highlight) => (
            <li key={highlight.en} className="max-w-[64ch]">
              {highlight[key]}
            </li>
          ))}
        </ul>
      </section>

      {project.metrics.length > 0 ? (
        <dl className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3">
          {project.metrics.map((metric) => (
            <div
              key={metric.label.en}
              className="tile flex flex-col gap-1 !p-4"
            >
              <dd className="stat-num numeric text-2xl font-extrabold">
                {metric.value}
              </dd>
              <dt className="text-xs text-muted-foreground">
                {metric.label[key]}
                {metric.note ? ` — ${metric.note[key]}` : null}
              </dt>
            </div>
          ))}
        </dl>
      ) : null}

      {project.private && project.privateNote ? (
        <p className="mt-6 max-w-[64ch] rounded-[var(--radius-md)] border border-dashed p-4 text-sm text-muted-foreground">
          {project.privateNote[key]}
        </p>
      ) : null}

      {project.caseStudy ? (
        <div className="mt-10 border-t pt-10">
          <CaseStudy caseStudy={project.caseStudy} locale={key} />
        </div>
      ) : null}

      {project.video ? (
        <section className="mt-10">
          <h2 className="text-xl font-semibold">{t("watchDemo")}</h2>
          <div className="mt-3">
            <VideoPlayer
              src={project.video.src}
              poster={project.video.poster}
              alt={project.coverAlt[key]}
            />
          </div>
        </section>
      ) : null}

      {project.gallery.length > 0 ? (
        <section className="mt-10">
          <h2 className="text-xl font-semibold">{t("gallery")}</h2>
          <div className="mt-3">
            <Gallery
              items={project.gallery.map((image) => ({
                src: image.src,
                alt: image.alt[key],
                caption: image.caption?.[key],
              }))}
            />
          </div>
        </section>
      ) : null}

      <nav
        aria-label={t("backToWork")}
        className="mt-12 flex justify-between gap-4 border-t pt-6 text-sm"
      >
        {previous ? (
          <Link href={`/projects/${previous.slug}`} className="group min-w-0">
            <span className="eyebrow block">{t("previous")}</span>
            <span className="mt-1 block underline-offset-4 group-hover:underline">
              {previous.title[key]}
            </span>
          </Link>
        ) : (
          <span />
        )}
        {next ? (
          <Link
            href={`/projects/${next.slug}`}
            className="group min-w-0 text-end"
          >
            <span className="eyebrow block">{t("next")}</span>
            <span className="mt-1 block underline-offset-4 group-hover:underline">
              {next.title[key]}
            </span>
          </Link>
        ) : null}
      </nav>
    </article>
  );
}
